const CATEGORY_ORDER = [
  'Салаты',
  'Основные блюда',
  'Супы',
  'Паста',
  'Хоспер меню',
  'Десерты',
  'Кавказские шашлыки',
  'Роллы',
  'Пицца',
  'Закуски',
  'Кофе и чай',
  'Безалкогольные',
  'Алкогольные'
];

const MENU = [
  // ——— Салаты ———
  { id: 'sl0', cat: 'Салаты', name: 'Руккола с креветками', price: 4500 },
  { id: 'sl1', cat: 'Салаты', name: 'Цезарь с курицей', price: 2960 },
  { id: 'sl2', cat: 'Салаты', name: 'Цезарь с креветками', price: 3450 },
  { id: 'sl3', cat: 'Салаты', name: 'Цезарь с сёмгой', price: 3450 },
  { id: 'sl4', cat: 'Салаты', name: 'Тёплый салат с говядиной', price: 2240 },
  { id: 'sl5', cat: 'Салаты', name: 'Салат с бурратой', price: 3440 },
  { id: 'sl6', cat: 'Салаты', name: 'Хрустящий баклажан', price: 2100 },
  { id: 'sl7', cat: 'Салаты', name: 'Греческий салат', price: 1940 },
  { id: 'sl8', cat: 'Салаты', name: 'Сезонный салат', price: 1360 },
  { id: 'sl9', cat: 'Салаты', name: 'Салат от шефа', price: 2360 },
  { id: 'sl10', cat: 'Салаты', name: 'Клап сендвич Жульен', price: 2370 },

  // ——— Вторые блюда ———
  { id: 'm0', cat: 'Основные блюда', name: 'Телятина с грибами в сливочном соусе', price: 3050 },
  { id: 'm1', cat: 'Основные блюда', name: 'Куриное филе на гриле', price: 3250 },
  { id: 'm2', cat: 'Основные блюда', name: 'Форель на гриле', price: 5700 },
  { id: 'm3', cat: 'Основные блюда', name: 'Сёмга в сливочном соусе', price: 5900 },
  { id: 'm4', cat: 'Основные блюда', name: 'Сёмга на пару', price: 4150 },
  { id: 'm5', cat: 'Основные блюда', name: 'Курица по-тайски', price: 3250 },

  // ——— Супы ———
  { id: 's0', cat: 'Супы', name: 'Рамен с курицей', price: 2700 },
  { id: 's1', cat: 'Супы', name: 'Рамен с говядиной', price: 2800 },
  { id: 's2', cat: 'Супы', name: 'Том-ям', price: 4100 },
  { id: 's3', cat: 'Супы', name: 'Чечевичный крем-суп', price: 1790 },
  { id: 's4', cat: 'Супы', name: 'Солянка сборная', price: 2100 },

  // ——— Паста ———
  { id: 'pa0', cat: 'Паста', name: 'Фетучини Альфредо', price: 2360 },
  { id: 'pa1', cat: 'Паста', name: 'Фетучини с сёмгой', price: 2650 },
  { id: 'pa2', cat: 'Паста', name: 'Спагетти болоньезе', price: 2450 },
  { id: 'pa3', cat: 'Паста', name: 'Фетучини с медальонами', price: 4200 },

  // ——— Хоспер ———
  { id: 'hm0', cat: 'Хоспер меню', name: 'Рибай говядина', price: 7800 },
  { id: 'hm1', cat: 'Хоспер меню', name: 'Рибай конина', price: 7200 },
  { id: 'hm2', cat: 'Хоспер меню', name: 'Ти-бон говядина', price: 7500 },
  { id: 'hm3', cat: 'Хоспер меню', name: 'Ассорти колбасок', price: 5310 },
  { id: 'hm4', cat: 'Хоспер меню', name: 'Медальоны из говядины', price: 6000 },
  { id: 'hm5', cat: 'Хоспер меню', name: 'Стейк из сёмги', price: 5600 },
  { id: 'hm6', cat: 'Хоспер меню', name: 'Говяжьи рёбра от шефа', price: 7600 },
  { id: 'hm7', cat: 'Хоспер меню', name: 'Мясной сет', price: 30000, desc: 'На 7–8 человек.' },
  { id: 'hm8', cat: 'Хоспер меню', name: 'Куриный сет', price: 11300 },
  { id: 'hm9', cat: 'Хоспер меню', name: 'Башня из медальонов из телятины', price: 6450 },

  // ——— Десерты ———
  { id: 'd0', cat: 'Десерты', name: 'Чизкейк испанский', price: 2500 },
  { id: 'd1', cat: 'Десерты', name: 'Чизкейк классика', price: 2250 },
  { id: 'd2', cat: 'Десерты', name: 'Фруктовая нарезка', price: 7000 },
  { id: 'd3', cat: 'Десерты', name: 'Шоколад' },
  { id: 'd4', cat: 'Десерты', name: 'Мороженое в ассортименте' },

  // ——— Кавказские шашлыки ———
  { id: 'sh0', cat: 'Кавказские шашлыки', name: 'Баранина мякоть', price: 3400 },
  { id: 'sh1', cat: 'Кавказские шашлыки', name: 'Ребрышки', price: 4300 },
  { id: 'sh2', cat: 'Кавказские шашлыки', name: 'Жамбас', price: 5400 },
  { id: 'sh3', cat: 'Кавказские шашлыки', name: 'Конина', price: 3700 },
  { id: 'sh4', cat: 'Кавказские шашлыки', name: 'Говядина', price: 3200 },
  { id: 'sh5', cat: 'Кавказские шашлыки', name: 'Печень', price: 2300 },
  { id: 'sh6', cat: 'Кавказские шашлыки', name: 'Наполеон', price: 3000 },
  { id: 'sh7', cat: 'Кавказские шашлыки', name: 'Люля кебаб', price: 2800 },
  { id: 'sh8', cat: 'Кавказские шашлыки', name: 'Утиная грудка', price: 2500 },
  { id: 'sh9', cat: 'Кавказские шашлыки', name: 'Крылышки', price: 2100 },
  { id: 'sh10', cat: 'Кавказские шашлыки', name: 'Курица', price: 2100 },
  { id: 'sh11', cat: 'Кавказские шашлыки', name: 'Скумбрия', price: 2700 },
  { id: 'sh12', cat: 'Кавказские шашлыки', name: 'Шампиньоны', price: 1500 },
  { id: 'sh13', cat: 'Кавказские шашлыки', name: 'Овощной шашлык', price: 1500 },
  { id: 'sh14', cat: 'Кавказские шашлыки', name: 'Ассорти шашлык', price: 15000 },

  // ——— Роллы ———
  { id: 'r0', cat: 'Роллы', name: 'Филадельфия классик', price: 3250 },
  { id: 'r1', cat: 'Роллы', name: 'Америка ролл с угрем', price: 3250 },
  { id: 'r2', cat: 'Роллы', name: 'Саке темпура', price: 3000 },
  { id: 'r3', cat: 'Роллы', name: 'Лас-Вегас', price: 3250 },
  { id: 'r4', cat: 'Роллы', name: 'Америка с креветками', price: 3250 },

  // ——— Пицца ———
  { id: 'p0', cat: 'Пицца', name: 'Пепперони', price: 3300 },
  { id: 'p1', cat: 'Пицца', name: 'Маргарита', price: 2200 },
  { id: 'p2', cat: 'Пицца', name: 'Болоньезе', price: 3000 },
  { id: 'p3', cat: 'Пицца', name: 'Цезарь', price: 4050 },
  { id: 'p4', cat: 'Пицца', name: 'Четыре сезона', price: 2850 },
  { id: 'p5', cat: 'Пицца', name: 'Хачапури по-мегрельски', price: 2600 },
  { id: 'p6', cat: 'Пицца', name: 'BBQ', price: 2000 },

  // ——— Закуски ———
  { id: 'zk0', cat: 'Закуски', name: 'Пивной сет (большой)', price: 10500 },
  { id: 'zk1', cat: 'Закуски', name: 'Пивной сет (маленький)', price: 6500 },
  { id: 'zk2', cat: 'Закуски', name: 'Русская закуска', price: 3990 },
  { id: 'zk3', cat: 'Закуски', name: 'Кавказская нарезка', price: 4500 },
  { id: 'zk4', cat: 'Закуски', name: 'Ассорти солений', price: 4200 },
  { id: 'zk5', cat: 'Закуски', name: 'Фри', price: 900 },
  { id: 'zk6', cat: 'Закуски', name: 'Острые крылышки Баффало', price: 3740 },
  { id: 'zk7', cat: 'Закуски', name: 'Наггетсы', price: 2200 },
  { id: 'zk8', cat: 'Закуски', name: 'Пивные креветки', price: 4700 },
  { id: 'zk9', cat: 'Закуски', name: 'Семечки к пиву', price: 4100 },
  { id: 'zk10', cat: 'Закуски', name: 'Гарлики', price: 1100 },
  { id: 'zk11', cat: 'Закуски', name: 'Луковые кольца', price: 1600 },
  { id: 'zk12', cat: 'Закуски', name: 'Жареный чечил', price: 1700 },
  { id: 'zk13', cat: 'Закуски', name: 'Картофельные дольки', price: 1100 },
  { id: 'zk14', cat: 'Закуски', name: 'Сырные палочки', price: 2450 },
  { id: 'zk15', cat: 'Закуски', name: 'Мозговые косточки', price: 2700 },

  // ——— Кофе и чай ———
  { id: 'k0', cat: 'Кофе и чай', subcat: 'Классические листовые чаи', name: 'Сенча', price: 1390, volume: '1 л', desc: 'Японский зеленый чай.' },
  { id: 'k1', cat: 'Кофе и чай', subcat: 'Классические листовые чаи', name: 'Жасмин', price: 1390, volume: '1 л', desc: 'Зеленый чай, ароматизированный цветами жасмина.' },
  { id: 'k2', cat: 'Кофе и чай', subcat: 'Классические листовые чаи', name: 'Ассам черный чай', price: 1090, volume: '1 л', desc: 'Классический черный листовой.' },
  { id: 'k3', cat: 'Кофе и чай', subcat: 'Классические листовые чаи', name: 'Молочный улун', price: 1390, volume: '1 л', desc: 'Зеленый листовой чай с ароматами молочных оттенков.' },
  { id: 'k4', cat: 'Кофе и чай', subcat: 'Авторские чаи', name: 'Ташкентский чай', price: 2290, volume: '1 л', desc: 'Цитрусовые фрукты, перечная мята, мёд, черный-зеленый листовой чай.' },
  { id: 'k5', cat: 'Кофе и чай', subcat: 'Авторские чаи', name: 'Марокканский чай', price: 2290, volume: '1 л', desc: 'Гренадин, анис, корица, гвоздика, черный листовой, перечная мята.' },
  { id: 'k6', cat: 'Кофе и чай', subcat: 'Авторские чаи', name: 'Имбирный чай', price: 2290, volume: '1 л', desc: 'Пюре имбирь, цитрусовые фрукты, мята, сенча, мёд.' },
  { id: 'k7', cat: 'Кофе и чай', subcat: 'Авторские чаи', name: 'Облепиха — Абрикос', price: 2290, volume: '1 л', desc: 'Пюре облепихи, пюре абрикос, черный листовой, цитрусовые фрукты, перечная мята, мёд.' },
  { id: 'k8', cat: 'Кофе и чай', subcat: 'Авторские чаи', name: 'Ягодный чай', price: 2290, volume: '1 л', desc: 'Пюре голубика, черный листовой, свежие ягоды, перечная мята.' },
  { id: 'k9', cat: 'Кофе и чай', subcat: 'Авторские чаи', name: 'Тропический твист', price: 2290, volume: '1 л', desc: 'Пюре персик, ананас, цитрусовые фрукты, перечная мята, сенча.' },
  { id: 'k10', cat: 'Кофе и чай', subcat: 'Дополнения к чаю', name: 'Лимон', price: 700 },
  { id: 'k11', cat: 'Кофе и чай', subcat: 'Дополнения к чаю', name: 'Апельсин', price: 700 },
  { id: 'k12', cat: 'Кофе и чай', subcat: 'Дополнения к чаю', name: 'Лайм', price: 700 },
  { id: 'k13', cat: 'Кофе и чай', subcat: 'Дополнения к чаю', name: 'Молоко', price: 700 },
  { id: 'k14', cat: 'Кофе и чай', subcat: 'Дополнения к чаю', name: 'Мёд', price: 700 },
  { id: 'k15', cat: 'Кофе и чай', subcat: 'Дополнения к чаю', name: 'Шоколад', price: 1400 },
  { id: 'k16', cat: 'Кофе и чай', subcat: 'Дополнения к чаю', name: 'Сироп в ассортименте', price: 700 },

  // ——— Безалкогольные ———
  { id: 'na0', cat: 'Безалкогольные', subcat: 'Лимонады', name: 'Тропический лимонад', price: 3290, volume: '1 л' },
  { id: 'na1', cat: 'Безалкогольные', subcat: 'Лимонады', name: 'Лесные ягоды', price: 3290, volume: '1 л' },
  { id: 'na2', cat: 'Безалкогольные', subcat: 'Лимонады', name: 'Персик — Ананас', price: 3290, volume: '1 л' },
  { id: 'na3', cat: 'Безалкогольные', subcat: 'Лимонады', name: 'Киви — Яблоко', price: 3290, volume: '1 л' },
  { id: 'na4', cat: 'Безалкогольные', subcat: 'Смузи / Детокс', name: 'Тропический смузи', price: 2790, volume: '0,3 л', desc: 'Пюре манго, пюре ананас, банан, апельсиновый сок.' },
  { id: 'na5', cat: 'Безалкогольные', subcat: 'Смузи / Детокс', name: 'Ягодный детокс', price: 2790, volume: '0,3 л', desc: 'Пюре ягод, свежие ягоды, яблочный сок.' },
  { id: 'na6', cat: 'Безалкогольные', subcat: 'Смузи / Детокс', name: 'Зеленый детокс', price: 2790, volume: '0,3 л', desc: 'Пюре киви, свежие яблоки, огурец, яблочный сок.' },
  { id: 'na7', cat: 'Безалкогольные', subcat: 'Милкшейки / Молочные коктейли', name: 'Персик — манго', price: 2890, volume: '0,3 л', desc: 'Сорбет из фруктов, пюре персика и манго, молоко.' },
  { id: 'na8', cat: 'Безалкогольные', subcat: 'Милкшейки / Молочные коктейли', name: 'Банан с ягодами', price: 2890, volume: '0,3 л', desc: 'Банан, пюре из ягод, сорбет клубники, молоко.' },
  { id: 'na9', cat: 'Безалкогольные', subcat: 'Милкшейки / Молочные коктейли', name: 'Ананас — кокос', price: 2890, volume: '0,3 л', desc: 'Пюре ананас, кокосовая стружка, ванильный пломбир, молоко.' },
  { id: 'na10', cat: 'Безалкогольные', subcat: 'Милкшейки / Молочные коктейли', name: 'Итальянский шоколад', price: 2890, volume: '0,3 л', desc: 'Банан, итальянский шоколад, пломбир из ванили, молоко.' },
  { id: 'na11', cat: 'Безалкогольные', subcat: 'Быстрые напитки / Soft Drinks', name: 'Tassay', price: 890 },
  { id: 'na12', cat: 'Безалкогольные', subcat: 'Быстрые напитки / Soft Drinks', name: 'Redbull в ассортименте', price: 1790 },
  { id: 'na13', cat: 'Безалкогольные', subcat: 'Быстрые напитки / Soft Drinks', name: 'Borjomi', price: 1690 },
  { id: 'na14', cat: 'Безалкогольные', subcat: 'Быстрые напитки / Soft Drinks', name: 'Coca-Cola / Fanta / Sprite', price: 990, volume: '0,25 л' },
  { id: 'na15', cat: 'Безалкогольные', subcat: 'Быстрые напитки / Soft Drinks', name: 'Coca-Cola', price: 1690, volume: '1 л' },
  { id: 'na16', cat: 'Безалкогольные', subcat: 'Быстрые напитки / Soft Drinks', name: 'Schweppes в ассортименте', price: 1690 },
  { id: 'na17', cat: 'Безалкогольные', subcat: 'Быстрые напитки / Soft Drinks', name: 'Piko в ассортименте', price: 1890 },
  { id: 'na18', cat: 'Безалкогольные', subcat: 'Безалкогольные коктейли / Non-alcoholic', name: 'Genry Toro', price: 2090, desc: 'Лайм, кордиал бузина, тонизирующий напиток.' },
  { id: 'na19', cat: 'Безалкогольные', subcat: 'Безалкогольные коктейли / Non-alcoholic', name: 'Mojito Classic', price: 2090, desc: 'Тростниковый сахар, перечная мята, лайм.' },
  { id: 'na20', cat: 'Безалкогольные', subcat: 'Безалкогольные коктейли / Non-alcoholic', name: 'Kyoto', price: 2090, desc: 'Пюре персик, кордиал бузина, черный чай.' },
  { id: 'na21', cat: 'Безалкогольные', subcat: 'Безалкогольные коктейли / Non-alcoholic', name: 'Aperol Spritz N/A', price: 2090, desc: 'Красный апельсин, тонизирующий напиток.' },

  // ——— Алкогольные ———
  { id: 'al0', cat: 'Алкогольные', subcat: 'Сигнатурные коктейли', name: 'Eclipse', price: 3190, desc: 'Кордиал маракуйя, светлый ром, кисло-сладкий баланс, облако из ванильной пены.' },
  { id: 'al1', cat: 'Алкогольные', subcat: 'Сигнатурные коктейли', name: 'Hemingway', price: 3190, desc: 'Бурбон, кордиал из вишни, пена.' },
  { id: 'al2', cat: 'Алкогольные', subcat: 'Сигнатурные коктейли', name: 'Soft-Tour', price: 3190, desc: 'Джин, кордиал бузина, тонизирующий напиток.' },
  { id: 'al3', cat: 'Алкогольные', subcat: 'Сигнатурные коктейли', name: 'Cosmopolitan-1985', price: 3190, desc: 'Водка, яблочный сок, кордиал граната, пена.' },
  { id: 'al4', cat: 'Алкогольные', subcat: 'Сигнатурные коктейли', name: 'V-Vento', price: 3190, desc: 'Джин, пюре персик, ваниль, игристое вино.' },
  { id: 'al5', cat: 'Алкогольные', subcat: 'Классические коктейли', name: 'Daiquiri', price: 2790 },
  { id: 'al6', cat: 'Алкогольные', subcat: 'Классические коктейли', name: 'Long Island Iced Tea', price: 3390 },
  { id: 'al7', cat: 'Алкогольные', subcat: 'Классические коктейли', name: 'White Russian', price: 2790 },
  { id: 'al8', cat: 'Алкогольные', subcat: 'Классические коктейли', name: 'Aperol Spritz', price: 2790 },
  { id: 'al9', cat: 'Алкогольные', subcat: 'Классические коктейли', name: 'Bellini', price: 2790 },
  { id: 'al10', cat: 'Алкогольные', subcat: 'Классические коктейли', name: 'Gin-Tonic', price: 2790 },
  { id: 'al11', cat: 'Алкогольные', subcat: 'Классические коктейли', name: 'Negroni', price: 2790 },
  { id: 'al12', cat: 'Алкогольные', subcat: 'Классические коктейли', name: 'Porn Star', price: 2790 },
  { id: 'al13', cat: 'Алкогольные', subcat: 'Классические коктейли', name: 'Whiskey Sour', price: 2790 },
  { id: 'al14', cat: 'Алкогольные', subcat: 'Классические коктейли', name: 'Mojito Alc', price: 2790 },
  { id: 'al15', cat: 'Алкогольные', subcat: 'Водка', name: 'Grey Goose', price: 2390, volume: '50 мл' },
  { id: 'al16', cat: 'Алкогольные', subcat: 'Водка', name: 'Belvedere Organic', price: 3790, volume: '50 мл' },
  { id: 'al17', cat: 'Алкогольные', subcat: 'Водка', name: 'Absolut Original', price: 1590, volume: '50 мл' },
  { id: 'al18', cat: 'Алкогольные', subcat: 'Водка', name: 'Absolut Elyx', price: 2190, volume: '50 мл' },
  { id: 'al19', cat: 'Алкогольные', subcat: 'Водка', name: 'Onegin', price: 2390, volume: '50 мл' },
  { id: 'al20', cat: 'Алкогольные', subcat: 'Водка', name: 'Koskenkorva', price: 1290, volume: '50 мл' },
  { id: 'al21', cat: 'Алкогольные', subcat: 'Водка', name: 'Stolichnaya', price: 1090, volume: '50 мл' },
  { id: 'al22', cat: 'Алкогольные', subcat: 'Водка', name: 'Kyzylzhar', price: 990, volume: '50 мл' },
  { id: 'al23', cat: 'Алкогольные', subcat: 'Водка', name: 'Архангельская', price: 990, volume: '50 мл' },
  { id: 'al24', cat: 'Алкогольные', subcat: 'Вермут', name: 'Martini Fiero', price: 1590, volume: '100 мл' },
  { id: 'al25', cat: 'Алкогольные', subcat: 'Вермут', name: 'Martini Bianco', price: 1590, volume: '100 мл' },
  { id: 'al26', cat: 'Алкогольные', subcat: 'Виски', name: 'Four Roses Original', price: 1790, volume: '50 мл' },
  { id: 'al27', cat: 'Алкогольные', subcat: 'Виски', name: 'Jack Daniel\'s', price: 2490, volume: '50 мл' },
  { id: 'al28', cat: 'Алкогольные', subcat: 'Пуэрто-риканский ром', name: 'Bacardi Carta Blanca', price: 1490, volume: '50 мл' },
  { id: 'al29', cat: 'Алкогольные', subcat: 'Пуэрто-риканский ром', name: 'Bacardi Carta Negra', price: 1490, volume: '50 мл' },
  { id: 'al30', cat: 'Алкогольные', subcat: 'Пуэрто-риканский ром', name: 'Bacardi Spiced', price: 1490, volume: '50 мл' },
  { id: 'al31', cat: 'Алкогольные', subcat: 'Пуэрто-риканский ром', name: 'Oakheart Original', price: 1490, volume: '50 мл' },
  { id: 'al32', cat: 'Алкогольные', subcat: 'Текила', name: 'Patron Silver', price: 2490, volume: '50 мл' },
  { id: 'al33', cat: 'Алкогольные', subcat: 'Текила', name: 'Patron Reposado', price: 2790, volume: '50 мл' },
  { id: 'al34', cat: 'Алкогольные', subcat: 'Текила', name: 'Olmeca Silver', price: 1590, volume: '50 мл' },
  { id: 'al35', cat: 'Алкогольные', subcat: 'Текила', name: 'Olmeca Gold', price: 1590, volume: '50 мл' },
  { id: 'al36', cat: 'Алкогольные', subcat: 'Текила', name: 'Olmeca Altos 100% Agave', price: 1690, volume: '50 мл' },
  { id: 'al37', cat: 'Алкогольные', subcat: 'Джин', name: 'Bombay Sapphire', price: 1690, volume: '50 мл' },
  { id: 'al38', cat: 'Алкогольные', subcat: 'Ликеры', name: 'Jagermeister', price: 2390, volume: '50 мл' },
  { id: 'al39', cat: 'Алкогольные', subcat: 'Ликеры', name: 'Aperol', price: 2390, volume: '50 мл' },
  { id: 'al40', cat: 'Алкогольные', subcat: 'Ликеры', name: 'Cointreau', price: 2390, volume: '50 мл' },
  { id: 'al41', cat: 'Алкогольные', subcat: 'Ликеры', name: 'Baileys', price: 2390, volume: '50 мл' },
  { id: 'al42', cat: 'Алкогольные', subcat: 'Ликеры', name: 'Kahlua', price: 2390, volume: '50 мл' },
  { id: 'al43', cat: 'Алкогольные', subcat: 'Ликеры', name: 'Campari', price: 2390, volume: '50 мл' },
  { id: 'al44', cat: 'Алкогольные', subcat: 'Вина по бокалам', name: 'San Valentin White белое сухое', price: 2090, volume: '150 мл' },
  { id: 'al45', cat: 'Алкогольные', subcat: 'Вина по бокалам', name: 'San Valentin Red красное сухое', price: 2090, volume: '150 мл' },
  { id: 'al46', cat: 'Алкогольные', subcat: 'Вина по бокалам', name: 'Крафтовое красное полусладкое', price: 1790, volume: '150 мл' },
  { id: 'al47', cat: 'Алкогольные', subcat: 'Вина по бокалам', name: 'Крафтовое белое полусладкое', price: 1790, volume: '150 мл' },
  { id: 'al48', cat: 'Алкогольные', subcat: 'Вино Новая Зеландия', name: 'Nuala Pinot Noir красное сухое', price: 27000 },
  { id: 'al49', cat: 'Алкогольные', subcat: 'Вино Новая Зеландия', name: 'Nuala Sauvignon Blanc белое сухое', price: 27000 },
  { id: 'al50', cat: 'Алкогольные', subcat: 'Вино Испания', name: 'Silk Spice Road красное сухое', price: 16000 },
  { id: 'al51', cat: 'Алкогольные', subcat: 'Вино Испания', name: 'Silk Spice White Blend', price: 16000 },
  { id: 'al52', cat: 'Алкогольные', subcat: 'Вино Италия', name: 'Canti Chardonnay белое полусладкое', price: 18000 },
  { id: 'al53', cat: 'Алкогольные', subcat: 'Вино Италия', name: 'Canti Merlot Veneto', price: 18000 },
  { id: 'al54', cat: 'Алкогольные', subcat: 'Вино Грузия', name: 'Киндзмараули красное полусладкое', price: 12000 },
  { id: 'al55', cat: 'Алкогольные', subcat: 'Вино Грузия', name: 'Саперави красное сухое', price: 10000 },
  { id: 'al56', cat: 'Алкогольные', subcat: 'Вино Грузия', name: 'Цинандали белое сухое', price: 10000 },
  { id: 'al57', cat: 'Алкогольные', subcat: 'Вино Грузия', name: 'Хванчкара', price: 15000 },
  { id: 'al58', cat: 'Алкогольные', subcat: 'Игристые вина', name: 'Martini Prosecco D.O.C', price: 15500 },
  { id: 'al59', cat: 'Алкогольные', subcat: 'Игристые вина', name: 'Martini Asti D.O.C.G', price: 15500 },
  { id: 'al60', cat: 'Алкогольные', subcat: 'Игристые вина', name: 'Martini Brut', price: 15500 },
  { id: 'al61', cat: 'Алкогольные', subcat: 'Игристые вина', name: 'Lambrusco Dell\'Emilia IGT', price: 9500 },
  { id: 'al62', cat: 'Алкогольные', subcat: 'Пиво разливное', name: 'Yichang', price: 1190, volume: '0,5 л' },
  { id: 'al63', cat: 'Алкогольные', subcat: 'Пиво разливное', name: 'Прага', price: 990, volume: '0,5 л' },
  { id: 'al64', cat: 'Алкогольные', subcat: 'Пиво бутылочное', name: 'Corona Extra', price: 2690, volume: '0,33 л' },
  { id: 'al65', cat: 'Алкогольные', subcat: 'Пиво бутылочное', name: 'Tsingtao', price: 1890, volume: '0,64 л' },
  { id: 'al66', cat: 'Алкогольные', subcat: 'Пиво бутылочное', name: 'Tsingtao 0%', price: 1690 },
  { id: 'al67', cat: 'Алкогольные', subcat: 'Пиво бутылочное', name: 'Stella Artois', price: 1790 },
  { id: 'al68', cat: 'Алкогольные', subcat: 'Пиво бутылочное', name: 'Stella Artois 0%', price: 1590 },
  { id: 'al69', cat: 'Алкогольные', subcat: 'Пиво бутылочное', name: 'Guinness Draught', price: 3090 },
  { id: 'al70', cat: 'Алкогольные', subcat: 'Пиво бутылочное', name: 'Miller', price: 1990 },
  { id: 'al71', cat: 'Алкогольные', subcat: 'Снэки к пиву', name: 'Чечил', price: 1290 },
  { id: 'al72', cat: 'Алкогольные', subcat: 'Снэки к пиву', name: 'Курт', price: 1090 },
  { id: 'al73', cat: 'Алкогольные', subcat: 'Снэки к пиву', name: 'Фисташки', price: 1490 },
  { id: 'al74', cat: 'Алкогольные', subcat: 'Снэки к пиву', name: 'Арахис', price: 1090 },
  { id: 'al75', cat: 'Алкогольные', subcat: 'Снэки к пиву', name: 'Чипсы', price: 1490 }
];

MENU.forEach((item, idx) => {
  item.uid = `item-${idx}`;
});
