/* Auto-generated dish photos — relative paths for GitHub Pages */
const IMAGE_MAP = {
  "sl0": "image/dishes/sl0.jpg",
  "sl1": "image/dishes/sl1.jpg",
  "sl2": "image/dishes/sl2.jpg",
  "sl3": "image/dishes/sl3.jpg",
  "sl4": "image/dishes/sl4.jpg",
  "sl5": "image/dishes/sl5.jpg",
  "sl6": "image/dishes/sl6.jpg",
  "sl7": "image/dishes/sl7.jpg",
  "sl8": "image/dishes/sl8.jpg",
  "sl9": "image/dishes/sl9.jpg",
  "sl10": "image/dishes/sl10.jpg",
  "m0": "image/dishes/m0.jpg",
  "m1": "image/dishes/m1.jpg",
  "m2": "image/dishes/m2.jpg",
  "m3": "image/dishes/m3.jpg",
  "m4": "image/dishes/m4.jpg",
  "m5": "image/dishes/m5.jpg",
  "s0": "image/dishes/s0.jpg",
  "s1": "image/dishes/s1.jpg",
  "s2": "image/dishes/s2.jpg",
  "s3": "image/dishes/s3.jpg",
  "s4": "image/dishes/s4.jpg",
  "pa0": "image/dishes/pa0.jpg",
  "pa1": "image/dishes/pa1.jpg",
  "pa2": "image/dishes/pa2.jpg",
  "pa3": "image/dishes/pa3.jpg",
  "hm0": "image/dishes/hm0.jpg",
  "hm1": "image/dishes/hm1.jpg",
  "hm2": "image/dishes/hm2.jpg",
  "hm3": "image/dishes/hm3.jpg",
  "hm4": "image/dishes/hm4.jpg",
  "hm5": "image/dishes/hm5.jpg",
  "hm6": "image/dishes/hm6.jpg",
  "hm7": "image/dishes/hm7.jpg",
  "hm8": "image/dishes/hm8.jpg",
  "hm9": "image/dishes/hm9.jpg",
  "d0": "image/dishes/d0.jpg",
  "d1": "image/dishes/d1.jpg",
  "d2": "image/dishes/d2.jpg",
  "d3": "image/dishes/d3.jpg",
  "d4": "image/dishes/d4.jpg",
  "sh0": "image/dishes/sh0.jpg",
  "sh1": "image/dishes/sh1.jpg",
  "sh2": "image/dishes/sh2.jpg",
  "sh3": "image/dishes/sh3.jpg",
  "sh4": "image/dishes/sh4.jpg",
  "sh5": "image/dishes/sh5.jpg",
  "sh6": "image/dishes/sh6.jpg",
  "sh7": "image/dishes/sh7.jpg",
  "sh8": "image/dishes/sh8.jpg",
  "sh9": "image/dishes/sh9.jpg",
  "sh10": "image/dishes/sh10.jpg",
  "sh11": "image/dishes/sh11.jpg",
  "sh12": "image/dishes/sh12.jpg",
  "sh13": "image/dishes/sh13.jpg",
  "sh14": "image/dishes/sh14.jpg",
  "r0": "image/dishes/r0.jpg",
  "r1": "image/dishes/r1.jpg",
  "r2": "image/dishes/r2.jpg",
  "r3": "image/dishes/r3.jpg",
  "r4": "image/dishes/r4.jpg",
  "p0": "image/dishes/p0.jpg",
  "p1": "image/dishes/p1.jpg",
  "p2": "image/dishes/p2.jpg",
  "p3": "image/dishes/p3.jpg",
  "p4": "image/dishes/p4.jpg",
  "p5": "image/dishes/p5.jpg",
  "p6": "image/dishes/p6.jpg",
  "zk0": "image/dishes/zk0.jpg",
  "zk1": "image/dishes/zk1.jpg",
  "zk2": "image/dishes/zk2.jpg",
  "zk3": "image/dishes/zk3.jpg",
  "zk4": "image/dishes/zk4.jpg",
  "zk5": "image/dishes/zk5.jpg",
  "zk6": "image/dishes/zk6.jpg",
  "zk7": "image/dishes/zk7.jpg",
  "zk8": "image/dishes/zk8.jpg",
  "zk9": "image/dishes/zk9.jpg",
  "zk10": "image/dishes/zk10.jpg",
  "zk11": "image/dishes/zk11.jpg",
  "zk12": "image/dishes/zk12.jpg",
  "zk13": "image/dishes/zk13.jpg",
  "zk14": "image/dishes/zk14.jpg",
  "zk15": "image/dishes/zk15.jpg"
};

if (typeof MENU !== 'undefined') {
  MENU.forEach(item => {
    if (IMAGE_MAP[item.id]) item.image = IMAGE_MAP[item.id];
  });
}
