/* Auto-generated by scripts/assign-photos.js — do not edit by hand */
const IMAGE_MAP = {
  "sl0": "/image/dishes/sl0.jpg",
  "sl1": "/image/dishes/sl1.jpg",
  "sl2": "/image/dishes/sl2.jpg",
  "sl3": "/image/dishes/sl3.jpg",
  "sl5": "/image/dishes/sl5.jpg",
  "sl6": "/image/dishes/sl6.jpg",
  "sl7": "/image/dishes/sl7.jpg",
  "m0": "/image/dishes/m0.jpg",
  "m1": "/image/dishes/m1.jpg",
  "m5": "/image/dishes/m5.jpg",
  "s2": "/image/dishes/s2.jpg",
  "pa0": "/image/dishes/pa0.jpg",
  "pa3": "/image/dishes/pa3.jpg",
  "d0": "/image/dishes/d0.jpg",
  "d1": "/image/dishes/d1.jpg",
  "d2": "/image/dishes/d2.jpg",
  "d3": "/image/dishes/d3.jpg",
  "d4": "/image/dishes/d4.jpg",
  "sh0": "/image/dishes/sh0.jpg",
  "p0": "/image/dishes/p0.jpg",
  "p1": "/image/dishes/p1.jpg"
};

if (typeof MENU !== 'undefined') {
  MENU.forEach(item => {
    if (IMAGE_MAP[item.id]) item.image = IMAGE_MAP[item.id];
  });
}
