require('dotenv').config();

const fs = require('fs');
const path = require('path');
const { initDb, db } = require('../server/db');
const { optimizeImage, listDishPhotos } = require('../pipeline/convert');
const { pickBestMatch, pickForUnmatched } = require('../pipeline/matcher');
const { analyzeImage, searchFoodHint } = require('../pipeline/vision');

initDb();

const imageDir = path.join(process.cwd(), 'image');
const optimizedDir = path.join(process.cwd(), 'image', 'optimized');
fs.mkdirSync(optimizedDir, { recursive: true });

const getItems = db.prepare(`
  SELECT mi.*, c.name AS category_name
  FROM menu_items mi
  JOIN categories c ON c.id = mi.category_id
  WHERE mi.active = 1
  ORDER BY mi.sort_order
`);

const updateImage = db.prepare(`
  UPDATE menu_items SET
    image_path = ?, image_source = ?, match_confidence = ?, updated_at = datetime('now')
  WHERE id = ?
`);

const insertMatch = db.prepare(`
  INSERT INTO image_matches (source_file, menu_item_id, confidence, method, vision_notes)
  VALUES (?, ?, ?, ?, ?)
`);

async function run() {
  const photos = listDishPhotos(imageDir);
  const items = getItems.all();

  if (!photos.length) {
    console.log('No dish photos found in /image folder.');
    return;
  }

  console.log(`Found ${photos.length} photos, ${items.length} menu items.`);
  console.log(process.env.OPENAI_API_KEY ? 'Vision API: enabled' : 'Vision API: disabled (using heuristic fallback)');

  const usedItemIds = new Set(
    items.filter(i => i.image_path).map(i => i.id)
  );

  let matched = 0;
  let skipped = 0;

  for (const photoPath of photos) {
    const basename = path.basename(photoPath);
    const outName = path.basename(photoPath, path.extname(photoPath)) + '.jpg';
    const outPath = path.join(optimizedDir, outName);
    const publicPath = `/image/optimized/${outName}`;

    try {
      if (!fs.existsSync(outPath)) {
        await optimizeImage(photoPath, outPath);
        console.log(`  Optimized: ${basename} → ${outName}`);
      }
    } catch (err) {
      console.warn(`  Skip ${basename}: ${err.message}`);
      skipped++;
      continue;
    }

    let method = 'heuristic';
    let confidence = 0;
    let matchedItem = null;
    let visionNotes = null;
    let tags = [];

    const vision = await analyzeImage(outPath, items);
    if (vision?.menuItemId) {
      matchedItem = items.find(i => i.id === vision.menuItemId);
      if (matchedItem) {
        method = 'openai-vision';
        confidence = vision.confidence || 0.8;
        visionNotes = JSON.stringify(vision);
        tags = [vision.dishName, ...(vision.ingredients || []), vision.style].filter(Boolean);
      }
    }

    if (!matchedItem && vision?.dishName) {
      const hints = await searchFoodHint(vision.dishName);
      tags = [...tags, ...hints];
    }

    if (!matchedItem) {
      const { item, confidence: c, score } = pickBestMatch(items, tags, basename, usedItemIds);
      if (item && score >= 3) {
        matchedItem = item;
        confidence = c;
        method = vision ? 'vision+heuristic' : 'heuristic';
      }
    }

    if (!matchedItem) {
      const foodFirst = items
        .filter(i => !usedItemIds.has(i.id))
        .sort((a, b) => {
          const drinkish = /алкогол|безалкогол|кофе|чай/i;
          const aDrink = drinkish.test(a.category_name) ? 1 : 0;
          const bDrink = drinkish.test(b.category_name) ? 1 : 0;
          return aDrink - bDrink;
        });
      matchedItem = pickForUnmatched(foodFirst, usedItemIds);
      if (matchedItem) {
        confidence = 0.2;
        method = 'sequential-fallback';
      }
    }

    if (!matchedItem || usedItemIds.has(matchedItem.id)) {
      console.log(`  Skip ${basename} — no free menu slot`);
      skipped++;
      continue;
    }

    updateImage.run(publicPath, method, confidence, matchedItem.id);
    insertMatch.run(basename, matchedItem.id, confidence, method, visionNotes);
    usedItemIds.add(matchedItem.id);
    matched++;

    console.log(`  ✓ ${basename} → ${matchedItem.name} (${Math.round(confidence * 100)}%, ${method})`);
  }

  // Write frontend image map so photos show even without waiting for API
  const withImages = db.prepare(`
    SELECT id, image_path FROM menu_items
    WHERE image_path IS NOT NULL AND image_path != ''
  `).all();

  const mapLines = withImages.map(r => `  ${JSON.stringify(r.id)}: ${JSON.stringify(r.image_path)}`).join(',\n');
  const mapJs = `/* Auto-generated by npm run match-images — do not edit by hand */\nconst IMAGE_MAP = {\n${mapLines}\n};\n\nif (typeof MENU !== 'undefined') {\n  MENU.forEach(item => {\n    if (IMAGE_MAP[item.id]) item.image = IMAGE_MAP[item.id];\n  });\n}\n`;
  fs.writeFileSync(path.join(process.cwd(), 'js', 'image-map.js'), mapJs, 'utf8');
  console.log(`\nWrote js/image-map.js (${withImages.length} images).`);

  console.log(`\nDone: ${matched} assigned, ${skipped} skipped.`);
  console.log(`${usedItemIds.size}/${items.length} items now have images.`);
}

run().catch(err => {
  console.error(err);
  process.exit(1);
});
